// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGl9-4IsQSQCVEMwAhT2wmIuhcY_qWDOw',
    appId: '1:846809172564:web:88034758fcb9fadf14bbc1',
    messagingSenderId: '846809172564',
    projectId: 'holydiary-6a58a',
    authDomain: 'holydiary-6a58a.firebaseapp.com',
    storageBucket: 'holydiary-6a58a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhFqZkgLSneckYaDtuWmiCzp4ALUU6jn8',
    appId: '1:846809172564:android:1ca9a92e9e39c18b14bbc1',
    messagingSenderId: '846809172564',
    projectId: 'holydiary-6a58a',
    storageBucket: 'holydiary-6a58a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnZgJeWP7Lxrlstpo5CdiZAKiILY76FBA',
    appId: '1:846809172564:ios:165e6f8baabf9bd514bbc1',
    messagingSenderId: '846809172564',
    projectId: 'holydiary-6a58a',
    storageBucket: 'holydiary-6a58a.appspot.com',
    iosClientId: '846809172564-ncb73moaovvn3bbgh5tl5e2vt3sk5oco.apps.googleusercontent.com',
    iosBundleId: 'com.example.holydiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnZgJeWP7Lxrlstpo5CdiZAKiILY76FBA',
    appId: '1:846809172564:ios:165e6f8baabf9bd514bbc1',
    messagingSenderId: '846809172564',
    projectId: 'holydiary-6a58a',
    storageBucket: 'holydiary-6a58a.appspot.com',
    iosClientId: '846809172564-ncb73moaovvn3bbgh5tl5e2vt3sk5oco.apps.googleusercontent.com',
    iosBundleId: 'com.example.holydiary',
  );
}
